baseURL = 'https://ninel.work/'
languageCode = 'en-us'
title = "Personal and Professional Development via Life-Long Learning"
theme = "hugo-paper-main"
canonifyURLs = "true"


[params]
  color = 'light'
  author = "Ninel Bolotova"
  description = "Ninel's take on various subjects she's interested in and worked with."
  taxonomiesExcludedFromSitemap = ["tags", "categories"]

[markup.goldmark.renderer]
unsafe= true


  [menu]
  [[menu.main]]
    identifier = '/'
    name = 'About'
    url = '/about/'
    weight = 10
  [[menu.main]]
    name = 'Articles'
    url = '/articles/'
    weight = 20
  [[menu.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 30
  [[menu.main]]
    name = 'Work with me'
    url = '/work-with-ninel/'
    weight = 40
    [menu.main.params]
    class = "header_nav_button"
