baseURL = 'https://ninel.work/'
languageCode = 'en-us'
title = "Personal and Professional Development via Life-Long Learning"
theme = "hugo-paper-main"
canonifyURLs = "true"


[params]
  color = 'light'
  author = "Ninel Bolotova"
  description = "Personal growth, skills improvement, professional certifications, good habits."
  taxonomiesExcludedFromSitemap = ["tags"]

[markup.goldmark.renderer]
unsafe= true


  [menu]
  [[menu.main]]
    identifier = '/'
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    name = 'Professional Growth'
    url = '/categories/professional-growth/'
    weight = 20
  [[menu.main]]
      name = 'Personal Growth'
      url = '/categories/personal-growth/'
      weight = 30
  [[menu.main]]
      name = 'About'
      url = '/about/'
      weight = 40
  [[menu.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 50
  [[menu.main]]
    name = 'Privacy Policy'
    url = '/privacy-policy/'
    weight = 60
  [[menu.main]]
    name = 'Coaching'
    url = '/personal-professional-development-coaching/'
    weight = 70
    [menu.main.params]
    class = "header_nav_button"
