baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Remote, Self-Education, No-Burnout & More. Blog by Ninel Bolotova"
theme = "hugo-paper-main"

[params]
  color = 'light'
  author = "Ninel Bolotova"
  description = "Ninel's take on various subjects she's interested in and worked with."
